services:
  ecommerce-app:
    image: "ecommerce-app"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jgrajber
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jgrajber
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80