spring:
  application:
    name: ecommerce-app
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080

allowed:
  origins: http://localhost:4200

okta:
  oauth2:
    client-id: 0oa6rr0pm8HP3jrmy5d7
    issuer: https://dev-96977370.okta.com/oauth2/default